eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 9412
spring:
  application:
    name: rabbit_server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
management:
  metrics:
    web:
      server:
        auto-time-requests: false