eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  application:
    name: gateway-server
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://127.0.0.1:9411
server:
  port: 5000
zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-server